spring:
  application:
    name: eazystore

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:~/estore;AUTO_SERVER=true
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10

  sql:
    init:
      mode: embedded
      schema-locations: optional:classpath:sql/schema.sql
      data-locations: optional:classpath:sql/data.sql
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.H2Dialect
logging:
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"
